module.exports = {
	add: require('./add.js'),
	diag: require('./diag.js'),
	frobenius: require('./frobenius.js'),
	elemWise: require('./elem-wise.js'),
	identity: require('./identity.js'),
	invert: require('./invert.js'),
	matMul: require('./mat-mul.js'),
	padWithZeroCols: require('./pad-with-zero-cols.js'),
	substract: require('./substract.js'),
	subSquareMatrix: require('./sub-square-matrix.js'),
	sum: require('./sum.js'),
	trace: require('./trace.js'),
	transpose: require('./transpose.js'),
	zeros: require('./zeros.js'),
};
